module.exports = [
  {
    "fName": "Jafar",
    "lName": "Zubair",
    "email": "zjzarjal@gmail.com",
    "Username": "Jafar",
    "phoneNumber": 9032757945,
    "country": "Nigeria",
    "institution": "University of Ibadan",
    "department": "Electrical and Electronics Engineering",
    "category": "Local Student "
  },
  {
    "fName": "Hudhayfah",
    "lName": "Ismail",
    "email": "hoismail2017@gmail.com",
    "Username": "Hudhayfah",
    "phoneNumber": 9053688477,
    "country": "Nigeria",
    "institution": "University of Ibadan",
    "department": "Electrical and Electronics Engineering",
    "category": "Local Student "
  },
  {
   "fName": "Abdulbasit",
   "lName": "Olayinka",
   "email": "yinkabasit@gmail.com",
   "Username": "Abdulbasit",
   "phoneNumber": 7043237005,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Local Student "
 },
 {
   "fName": "Abdullah Taiwo",
   "lName": "Adam",
   "email": "adamabdullahtaiwo15@gmail.com",
   "Username": "Abdullah Taiwo",
   "phoneNumber": 8064980572,
   "country": "Nigeria",
   "institution": "Ladoke akintola university of technology ",
   "department": "Electrical and electronics engineering ",
   "category": "Local Student "
 },
 {
   "fName": "Abdullahi",
   "lName": "Inusa",
   "email": "ainusa44@gmail.com",
   "Username": "Abdullahi",
   "phoneNumber": 8068482446,
   "country": "Nigeria",
   "institution": "Universiti Malaysia Sarawak (UNIMAS)",
   "department": "Electrical / Electronic Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Abdullateef",
   "lName": "Ogundipe",
   "email": "ogundipe72@gmail.com",
   "Username": "Abdullateef",
   "phoneNumber": 8065188043,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronc engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Abdulquadri",
   "lName": "Akindeere",
   "email": "akindeqk@gmail.com",
   "Username": "Abdulquadri",
   "phoneNumber": 8062345977,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Abdulquadri ",
   "lName": "Fagbenro",
   "email": "timilehinfagbenro@yahoo.com",
   "Username": "Abdulquadri ",
   "phoneNumber": 8101123569,
   "country": "Nigeria",
   "institution": "Ladoke Akintola University of Technology ",
   "department": "Electronics and Electrical Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Abiodun",
   "lName": "Alabi",
   "email": "aealabi@jabu.edu.ng",
   "Username": "Abiodun",
   "phoneNumber": 8133347441,
   "country": "Nigeria",
   "institution": "Joseph Ayo Babalola University Ikeji Arakeji Osun state",
   "department": "ICT Centre",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Abiodun",
   "lName": "Adeyeye",
   "email": "bidey2010@gmail.com",
   "Username": "Abiodun",
   "phoneNumber": 8032148108,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical & Electronic Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "ADEAGBO ",
   "lName": "MONSURU",
   "email": "Adeagbomonsoor@gmail.com",
   "Username": "ADEAGBO ",
   "phoneNumber": 8034648769,
   "country": "Nigeria",
   "institution": "Lautech",
   "department": "Computer Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Adedamola ",
   "lName": "Adeleke",
   "email": "adelekehabeebadedamola@gmail.com",
   "Username": "Adedamola ",
   "phoneNumber": 8135011093,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Adeolu",
   "lName": "George",
   "email": "deolugeorge@gmail.com",
   "Username": "Adeolu",
   "phoneNumber": 8055456809,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Adetokun",
   "lName": "Adeleke Goodness ",
   "email": "gadetokun@gmail.com",
   "Username": "Adetokun",
   "phoneNumber": 8133509569,
   "country": "Nigeria",
   "institution": "University of Ibadan, Nigeria ",
   "department": "Electrical/ Electronics Department ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Afis",
   "lName": "Akande",
   "email": "nugget4best2004@gmail.com",
   "Username": "Afis",
   "phoneNumber": 8038005191,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "AGBOOLA",
   "lName": "KOLAWOLE",
   "email": "Protocol42009@yahoo.com",
   "Username": "AGBOOLA",
   "phoneNumber": 8060737510,
   "country": "Nigeria",
   "institution": "Federal polytechnic ede ",
   "department": "Electrical and electronic ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Ahmed",
   "lName": "Mohammed Saba",
   "email": "msahmed5050@gmail.com",
   "Username": "Ahmed",
   "phoneNumber": 8038267621,
   "country": "Nigeria",
   "institution": "Ahmadu Bello University Zaria",
   "department": "Computer Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Arazim",
   "lName": "SHEU",
   "email": "arazimsheu@yahoo.com",
   "Username": "Arazim",
   "phoneNumber": 8030937283,
   "country": "Nigeria",
   "institution": "University of Ibadan ",
   "department": "Electrical Electronics Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Ayodeji",
   "lName": "Akinremi",
   "email": "akinremiaj24@gmail.com",
   "Username": "Ayodeji",
   "phoneNumber": 7039589803,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "BABAFEMI",
   "lName": "ADEYEMI",
   "email": "babafemiadeyemi@gmail.com",
   "Username": "BABAFEMI",
   "phoneNumber": 7069604630,
   "country": "Nigeria",
   "institution": "",
   "department": "Electrical & Electronic Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Babatunde",
   "lName": "Emmanuel",
   "email": "sbemmanuel@yahoo.com",
   "Username": "Babatunde",
   "phoneNumber": 8055825719,
   "country": "Nigeria",
   "institution": "Lead City University, Ibadan",
   "department": "Department of Electrical and Electronic Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "BAMIGBOYE",
   "lName": "OLADAYO OLADELE",
   "email": "bamigboye_dayo@yahoo.com",
   "Username": "BAMIGBOYE",
   "phoneNumber": 8034746024,
   "country": "Nigeria",
   "institution": "university of ibadan",
   "department": "electrical and electronics engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Damilare",
   "lName": "Atunbi",
   "email": "damilareatunbi@gmail.com",
   "Username": "Damilare",
   "phoneNumber": 8100717362,
   "country": "Nigeria",
   "institution": "University of Ilorin",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "DAUDA",
   "lName": "AROGUNDADE",
   "email": "dawud157@gmail.com",
   "Username": "DAUDA",
   "phoneNumber": 8052066269,
   "country": "Nigeria",
   "institution": "SOURCE OF PEACE ENERGY CONCEPT",
   "department": "ELECTRICAL/ELECTRONIC ENGINEERING",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Emmanuel",
   "lName": "Akut",
   "email": "eakut88@gmail.com",
   "Username": "Emmanuel",
   "phoneNumber": 8034564205,
   "country": "Nigeria",
   "institution": "Ahmadu Bello University, Zaria",
   "department": "Telecommunication Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Ephraim ",
   "lName": "Joseph ",
   "email": "akogwu20@gmail.com",
   "Username": "Ephraim ",
   "phoneNumber": 8137740164,
   "country": "Nigeria",
   "institution": "",
   "department": "Electrical and Electronics ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Esther",
   "lName": "Oyeleye",
   "email": "estherroyeleye@gmail.com",
   "Username": "Esther",
   "phoneNumber": 9067756473,
   "country": "Nigeria",
   "institution": "University of Ibadan ",
   "department": "Electrical/Electronic Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "ETEYEN",
   "lName": "UYO",
   "email": "uyoeteyen@gmail.com",
   "Username": "ETEYEN",
   "phoneNumber": 8032485982,
   "country": "Nigeria",
   "institution": "The university of Ibadan",
   "department": "Electrical/Electronics Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "FABIYI SAMUEL",
   "lName": "AKINTUNDE",
   "email": "sfabiyi535@sti.ui.edu.ng",
   "Username": "FABIYI SAMUEL",
   "phoneNumber": 9132480201,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Industrial and production Engineering",
   "category": "Local Student"
 },
 {
   "fName": "Gabriel",
   "lName": "Ogungbure",
   "email": "ogungburegabriel@gmail.com",
   "Username": "Gabriel",
   "phoneNumber": 7063542898,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronic Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Gideon",
   "lName": "Adekunle",
   "email": "adeksgt@gmail.com",
   "Username": "Gideon",
   "phoneNumber": 8133099386,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical/Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Goodness",
   "lName": "Adedeji",
   "email": "goodnessadedeji7@gmail.com",
   "Username": "Goodness",
   "phoneNumber": 8101006726,
   "country": "Nigeria",
   "institution": "",
   "department": "Department of Mechatronics Engineering",
   "category": "Local Student "
 },
 {
   "fName": "HAMMED",
   "lName": "BUSARI",
   "email": "hammed_busari@yahoo.com",
   "Username": "HAMMED",
   "phoneNumber": 7064990584,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronic ",
   "category": "Local Student "
 },
 {
   "fName": "Ilesanmi",
   "lName": "Adeleye",
   "email": "adeleyekayode070@gmail.com",
   "Username": "Ilesanmi",
   "phoneNumber": 7061294436,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Jeremiah",
   "lName": "Dosu",
   "email": "dosujerry1997@gmail.com",
   "Username": "Jeremiah",
   "phoneNumber": 9041775693,
   "country": "Nigeria",
   "institution": "Federal University of Technology Minna",
   "department": "Department of Mechatronics Engineering",
   "category": "Local Student "
 },
 {
   "fName": "John",
   "lName": "Odeleke",
   "email": "johnoluwasolaodeleke@gmail.com",
   "Username": "John",
   "phoneNumber": 8060173632,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronic Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "John",
   "lName": "funsoadebayo",
   "email": "funso@ieee.org",
   "Username": "John",
   "phoneNumber": 8074172133,
   "country": "Nigeria",
   "institution": "",
   "department": "",
   "category": ""
 },
 {
   "fName": "Joseph",
   "lName": "Fadiji",
   "email": "fadiji.joseph@st.futminna.edu.ng",
   "Username": "Joseph",
   "phoneNumber": 8091121186,
   "country": "Nigeria",
   "institution": "Federal University of Technology",
   "department": "Computer Engineering",
   "category": "Local Student "
 },
 {
   "fName": "Kamilu",
   "lName": "Suuti",
   "email": "akinsuuti@gmail.com",
   "Username": "Kamilu",
   "phoneNumber": 8060409625,
   "country": "Nigeria",
   "institution": "University of Ibadan, Ibadan.",
   "department": "EEE",
   "category": "Local Participant"
 },
 {
   "fName": "Kufre Esenowo",
   "lName": "Jack",
   "email": "kufre@futminna.edu.ng",
   "Username": "Kufre Esenowo",
   "phoneNumber": 8127958882,
   "country": "Nigeria",
   "institution": "FEDERAL UNIVERSITY OF TECHNOLOGY,MINNA,NIGER STATE",
   "department": "Department of Mechatronics Engineering , ",
   "category": "Local Participant"
 },
 {
   "fName": "LATEEF",
   "lName": "AKINYEMI",
   "email": "Lateef.akinyemi@alumni.uct.ac.za",
   "Username": "LATEEF",
   "phoneNumber": 8027413521,
   "country": "Nigeria",
   "institution": "Lagos State University and University of Cape Town",
   "department": "Electronic and Computer Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "Maxwell",
   "lName": "Chima",
   "email": "chymax20@yahoo.com",
   "Username": "Maxwell",
   "phoneNumber": 8067252222,
   "country": "Nigeria",
   "institution": "Federal Polytechnic Nekede, Owerri, Imo State",
   "department": "Electrical/Electronics Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "Michael",
   "lName": "Ayeni",
   "email": "ayenimichael22@gmail.com",
   "Username": "Michael",
   "phoneNumber": 8034207267,
   "country": "Nigeria",
   "institution": "The Polytechnic, Ibadan",
   "department": "Electrical Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "Michael ",
   "lName": "Irechukwu",
   "email": "enyimike@gmail.com",
   "Username": "Michael ",
   "phoneNumber": 256788000000,
   "country": "Uganda",
   "institution": "Kabale University",
   "department": "Department of Electrical Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "Mistura",
   "lName": "Muibi-Tijani",
   "email": "mistura@ieee.org",
   "Username": "Mistura",
   "phoneNumber": 8033607229,
   "country": "Nigeria",
   "institution": "IEEE Nigeria ",
   "department": "Young Professionals",
   "category": "Local Participant"
 },
 {
   "fName": "Motunrayo",
   "lName": "Ayodeji",
   "email": "ayodejimodupeola3@gmail.com",
   "Username": "Motunrayo",
   "phoneNumber": 8068989444,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Muhammad ",
   "lName": "Hashim ",
   "email": "mighteeyaks@gmail.com",
   "Username": "Muhammad ",
   "phoneNumber": 8142098802,
   "country": "Nigeria",
   "institution": "Kano State Polytechnic ",
   "department": "Electrical and Electronics engineering ",
   "category": "Local Participant"
 },
 {
   "fName": "MUTIU",
   "lName": "AGBOOLA",
   "email": "protocol42000@yahoo.com",
   "Username": "MUTIU",
   "phoneNumber": 8060737510,
   "country": "Nigeria",
   "institution": "FEDERAL POLYTECHNIC EDE, OSUN STATE",
   "department": "ELECTRICAL AND ELECTRONICS ENGINEERING",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "NURENI OLAWALE ",
   "lName": "OLANIRAN ",
   "email": "nureniolaniran@gmail.com",
   "Username": "NURENI OLAWALE ",
   "phoneNumber": 8140243322,
   "country": "Nigeria",
   "institution": "University of Ibadan ",
   "department": "Electrical/Electronic Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Okezie ",
   "lName": "Ozue",
   "email": "Okeziepg@gmail.com",
   "Username": "Okezie ",
   "phoneNumber": 7038262179,
   "country": "Nigeria",
   "institution": "",
   "department": "Electrical And Electronics Engineering ",
   "category": "Local Participant"
 },
 {
   "fName": "Olaide",
   "lName": "Oyedele",
   "email": "miyyah4me@gmail.com",
   "Username": "Olaide",
   "phoneNumber": 7031673115,
   "country": "Nigeria",
   "institution": "",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Olaide ",
   "lName": "AYOADE ",
   "email": "ayoadeolaide17@gmail.com",
   "Username": "Olaide ",
   "phoneNumber": 8137398322,
   "country": "Nigeria",
   "institution": "First Technical University Ibadan ",
   "department": "Biomedical engineering ",
   "category": "Local Student "
 },
 {
   "fName": "Olalekan",
   "lName": "Bada",
   "email": "gens3000@gmail.com",
   "Username": "Olalekan",
   "phoneNumber": 7055068384,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronic Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Olamide",
   "lName": "Aremu",
   "email": "olamidearemu1@gmail.com",
   "Username": "Olamide",
   "phoneNumber": 8134202596,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical/Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "OLUFEMI",
   "lName": "SONEYE",
   "email": "femisoneye10@gmail.com",
   "Username": "OLUFEMI",
   "phoneNumber": 8060004909,
   "country": "Nigeria",
   "institution": "UNIVERSITY OF IBADAN, IBADAN, OYO STATE, NIGERIA",
   "department": "ELECTRICAL AND ELECTRONIC ENGINEERING DEPARTMENT",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Oluseyi",
   "lName": "Adeyemi",
   "email": "adeyemi.oluseyi@gmail.com",
   "Username": "Oluseyi",
   "phoneNumber": 8155956769,
   "country": "Nigeria",
   "institution": "First Technical University, Ibadan.",
   "department": "Mechanical Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "Oluwabunmi",
   "lName": "Akomolafe",
   "email": "akomolafeoluwabunmi31@gmail.com",
   "Username": "Oluwabunmi",
   "phoneNumber": 8137892419,
   "country": "Nigeria",
   "institution": "Ladoke Akintola University of Technology ",
   "department": "Electronic and Electrical Engineering ",
   "category": "Local Participant"
 },
 {
   "fName": "Oluwagbenga ",
   "lName": "Apata",
   "email": "g.apata@ieee.org",
   "Username": "Oluwagbenga ",
   "phoneNumber": 8037270637,
   "country": "Nigeria",
   "institution": "University of Cape Town",
   "department": "Electrical Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Omomoluwa",
   "lName": "Omole",
   "email": "omoleomomoluwa22@gmail.com",
   "Username": "Omomoluwa",
   "phoneNumber": 8039263574,
   "country": "Nigeria",
   "institution": "UNIVERSITY OF IBADAN",
   "department": "ELECTRICAL & ELECTRONIC ENGINEERING ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Omotayo",
   "lName": "Ayodele",
   "email": "ayustayus86@gmail.com",
   "Username": "Omotayo",
   "phoneNumber": 7038912888,
   "country": "Nigeria",
   "institution": "University of Ibadan, Ibadan.",
   "department": "Electrical and Electronic Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "OPEYEMI",
   "lName": "ADEBISI",
   "email": "isaacopeyemi13@gmail.com",
   "Username": "OPEYEMI",
   "phoneNumber": 7030221494,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Peter",
   "lName": "Ehinlaiye ",
   "email": "peterehinlaiye@yahoo.com",
   "Username": "Peter",
   "phoneNumber": 8060577880,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Peter",
   "lName": "Oyedemi",
   "email": "oyedepeter@gmail.com",
   "Username": "Peter",
   "phoneNumber": 7069114899,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Raheemat",
   "lName": "Adefabi",
   "email": "raheematopeyemi@gmail.com",
   "Username": "Raheemat",
   "phoneNumber": 7036357054,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical Electronics Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Richard",
   "lName": "Olarewaju",
   "email": "dayorich2018@gmail.com",
   "Username": "Richard",
   "phoneNumber": 7060747826,
   "country": "Nigeria",
   "institution": "UNIVERSITY OF IBADAN",
   "department": "ELECTRICAL/ELECTRONIC ENGINEERING",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Saheed Adewole",
   "lName": "SUARA",
   "email": "uwec234@gmail.com",
   "Username": "Saheed Adewole",
   "phoneNumber": 7033614046,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical Electronics Engineering",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Salam Abdulganiy",
   "lName": "Ishola",
   "email": "isholaabdulganiy@gmail.com",
   "Username": "Salam Abdulganiy",
   "phoneNumber": 8153921619,
   "country": "Nigeria",
   "institution": "First technical University ibadan",
   "department": "Electrical and Electronics Engineering",
   "category": "International Participant"
 },
 {
   "fName": "Sanusi",
   "lName": "Abu Darma",
   "email": "darmasanusiabu@yahoo.com",
   "Username": "Sanusi",
   "phoneNumber": 109188176,
   "country": "Malaysia",
   "institution": "University Sultan Zainal Abidin, Terengganu, Malaysia",
   "department": "Informatics and Computing",
   "category": "International Student"
 },
 {
   "fName": "Sikirulahi",
   "lName": "Oyeleke",
   "email": "dhikrullahoyeleke@gmail.com",
   "Username": "Sikirulahi",
   "phoneNumber": 8130947160,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronic Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Simeon",
   "lName": "Ayodeji",
   "email": "adebayosimeon016@gmail.com",
   "Username": "Simeon",
   "phoneNumber": 8066364168,
   "country": "Nigeria",
   "institution": "University of Ibadan",
   "department": "Electrical and Electronics",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Sunday",
   "lName": "Salimon",
   "email": "sasalimon@lautech.edu.ng",
   "Username": "Sunday",
   "phoneNumber": 7039144922,
   "country": "Nigeria",
   "institution": "Ladoke Akintola University of Technology, Ogbomos",
   "department": "Electronic and Electrical Engineering",
   "category": "Local Participant"
 },
 {
   "fName": "Timileyin",
   "lName": "Fagbenro",
   "email": "timilehinfagbenro@yahoo.com",
   "Username": "Timileyin",
   "phoneNumber": 8148838028,
   "country": "Nigeria",
   "institution": "Ladoke Akintola University of Technology Ogbomoso",
   "department": "Electronic and Electrical Engineering",
   "category": "Local Student "
 },
 {
   "fName": "Tunde",
   "lName": "Adiamo",
   "email": "Adiamotunde015@gmail.com",
   "Username": "Tunde",
   "phoneNumber": 8100801100,
   "country": "Nigeria",
   "institution": "University of ibadan",
   "department": "Electrical and Electronics Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Victory",
   "lName": "Edema",
   "email": "evicyory@gmail.com",
   "Username": "Victory",
   "phoneNumber": 8164087537,
   "country": "Nigeria",
   "institution": "University of Ibadan ",
   "department": "Electrical and Electronic Engineering ",
   "category": "Postgraduate Session Participant"
 },
 {
   "fName": "Yusuf Kola",
   "lName": "Ahmed",
   "email": "ahmed.yk@unilorin.edu.ng",
   "Username": "Yusuf Kola",
   "phoneNumber": 7033916971,
   "country": "Nigeria",
   "institution": "University of Ilorin",
   "department": "Biomedical Engineering",
   "category": "Local Participant"
 }
]