module.exports = [
    {
      "fName": "Sunday",
      "lName": "Salimon",
      "email": "sasalimon@lautech.edu.ng",
      "Username": "Sunday",
      "phoneNumber": 7039144922,
      "country": "Nigeria",
      "institution": "Ladoke Akintola University of Technology, Ogbomos",
      "department": "Electronic and Electrical Engineering",
      "category": "Local Participant"
    },
    {
      "fName": "HAMMED",
      "lName": "BUSARI",
      "email": "hammed_busari@yahoo.com",
      "Username": "HAMMED",
      "phoneNumber": 7064990584,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronic ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Adeolu",
      "lName": "George",
      "email": "deolugeorge@gmail.com",
      "Username": "Adeolu",
      "phoneNumber": 8055456809,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "BABAFEMI",
      "lName": "ADEYEMI",
      "email": "babafemiadeyemi@gmail.com",
      "Username": "BABAFEMI",
      "phoneNumber": 7069604630,
      "country": "Nigeria",
      "institution": "",
      "department": "Electrical & Electronic Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Peter",
      "lName": "Ehinlaiye ",
      "email": "peterehinlaiye@yahoo.com",
      "Username": "Peter",
      "phoneNumber": 8060577880,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronics Engineering ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Olamide",
      "lName": "Aremu",
      "email": "olamidearemu1@gmail.com",
      "Username": "Olamide",
      "phoneNumber": 8134202596,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical/Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Raheemat",
      "lName": "Adefabi",
      "email": "raheematopeyemi@gmail.com",
      "Username": "Raheemat",
      "phoneNumber": 7036357054,
      "country": "Nigeria",
      "institution": "Nil",
      "department": "Electrical Electronics Engineering ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Kamilu",
      "lName": "Suuti",
      "email": "akinsuuti@gmail.com",
      "Username": "Kamilu",
      "phoneNumber": 8060409625,
      "country": "Nigeria",
      "institution": "University of Ibadan, Ibadan.",
      "department": "EEE",
      "category": "Local Participant"
    },
    {
      "fName": "Olaide",
      "lName": "Oyedele",
      "email": "miyyah4me@gmail.com",
      "Username": "Olaide",
      "phoneNumber": 7031673115,
      "country": "Nigeria",
      "institution": "",
      "department": "Electrical and Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Abiodun",
      "lName": "Alabi",
      "email": "aealabi@jabu.edu.ng",
      "Username": "Abiodun",
      "phoneNumber": 8133347441,
      "country": "Nigeria",
      "institution": "Joseph Ayo Babalola University Ikeji Arakeji Osun state",
      "department": "ICT Centre",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Omomoluwa",
      "lName": "Omole",
      "email": "omoleomomoluwa22@gmail.com",
      "Username": "Omomoluwa",
      "phoneNumber": 8039263574,
      "country": "Nigeria",
      "institution": "UNIVERSITY OF IBADAN",
      "department": "ELECTRICAL & ELECTRONIC ENGINEERING ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Adetokun",
      "lName": "Adeleke Goodness ",
      "email": "gadetokun@gmail.com",
      "Username": "Adetokun",
      "phoneNumber": 8133509569,
      "country": "Nigeria",
      "institution": "University of Ibadan, Nigeria ",
      "department": "Electrical/ Electronics Department ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "John",
      "lName": "Odeleke",
      "email": "johnoluwasolaodeleke@gmail.com",
      "Username": "John",
      "phoneNumber": 8060173632,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronic Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "OLUFEMI",
      "lName": "SONEYE",
      "email": "femisoneye10@gmail.com",
      "Username": "OLUFEMI",
      "phoneNumber": 8060004909,
      "country": "Nigeria",
      "institution": "UNIVERSITY OF IBADAN, IBADAN, OYO STATE, NIGERIA",
      "department": "ELECTRICAL AND ELECTRONIC ENGINEERING DEPARTMENT",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Oluwagbenga ",
      "lName": "Apata",
      "email": "g.apata@ieee.org",
      "Username": "Oluwagbenga ",
      "phoneNumber": 8037270637,
      "country": "Nigeria",
      "institution": "University of Cape Town",
      "department": "Electrical Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Babatunde",
      "lName": "Emmanuel",
      "email": "sbemmanuel@yahoo.com",
      "Username": "Babatunde",
      "phoneNumber": 8055825719,
      "country": "Nigeria",
      "institution": "Lead City University, Ibadan",
      "department": "Department of Electrical and Electronic Engineering",
      "category": "Local Participant"
    },
    {
      "fName": "Emmanuel",
      "lName": "Akut",
      "email": "eakut88@gmail.com",
      "Username": "Emmanuel",
      "phoneNumber": 8034564205,
      "country": "Nigeria",
      "institution": "Ahmadu Bello University, Zaria",
      "department": "Telecommunication Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Olugbenga",
      "lName": "Apata",
      "email": "adbade007@myuct.ac.za",
      "Username": "Olugbenga",
      "phoneNumber": 270839000000,
      "country": "South Africa",
      "institution": "University of Cape Town",
      "department": "Electrical Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Salam Abdulganiy",
      "lName": "Ishola",
      "email": "isholaabdulganiy@gmail.com",
      "Username": "Salam Abdulganiy",
      "phoneNumber": 8153921619,
      "country": "Nigeria",
      "institution": "First technical University ibadan",
      "department": "Electrical and Electronics Engineering",
      "category": "International Participant"
    },
    {
      "fName": "Abdullah Taiwo",
      "lName": "Adam",
      "email": "adamabdullahtaiwo15@gmail.com",
      "Username": "Abdullah Taiwo",
      "phoneNumber": 8064980572,
      "country": "Nigeria",
      "institution": "Ladoke akintola university of technology ",
      "department": "Electrical and electronics engineering ",
      "category": "Local Student "
    },
    {
      "fName": "Peter",
      "lName": "Oyedemi",
      "email": "oyedepeter@gmail.com",
      "Username": "Peter",
      "phoneNumber": 7069114899,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical Electronics Engineering",
      "category": "Local Student "
    },
    {
      "fName": "Abdulbasit",
      "lName": "Olayinka",
      "email": "yinkabasit@gmail.com",
      "Username": "Abdulbasit",
      "phoneNumber": 7043237005,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronics Engineering",
      "category": "Local Student "
    },
    {
      "fName": "Olaide ",
      "lName": "AYOADE ",
      "email": "ayoadeolaide17@gmail.com",
      "Username": "Olaide ",
      "phoneNumber": 8137398322,
      "country": "Nigeria",
      "institution": "First Technical University Ibadan ",
      "department": "Biomedical engineering ",
      "category": "Local Student "
    },
    {
      "fName": "Oluwabunmi",
      "lName": "Akomolafe",
      "email": "akomolafeoluwabunmi31@gmail.com",
      "Username": "Oluwabunmi",
      "phoneNumber": 8137892419,
      "country": "Nigeria",
      "institution": "Ladoke Akintola University of Technology ",
      "department": "Electronic and Electrical Engineering ",
      "category": "Local Participant"
    },
    {
      "fName": "Arazim",
      "lName": "SHEU",
      "email": "arazimsheu@yahoo.com",
      "Username": "Arazim",
      "phoneNumber": 8030937283,
      "country": "Nigeria",
      "institution": "University of Ibadan ",
      "department": "Electrical Electronics Engineering ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Abdullateef",
      "lName": "Ogundipe",
      "email": "ogundipe72@gmail.com",
      "Username": "Abdullateef",
      "phoneNumber": 8065188043,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronc engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Esther",
      "lName": "Oyeleye",
      "email": "estherroyeleye@gmail.com",
      "Username": "Esther",
      "phoneNumber": 9067756473,
      "country": "Nigeria",
      "institution": "University of Ibadan ",
      "department": "Electrical/Electronic Engineering ",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Saheed Adewole",
      "lName": "SUARA",
      "email": "uwec234@gmail.com",
      "Username": "Saheed Adewole",
      "phoneNumber": 7033614046,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Damilare",
      "lName": "Atunbi",
      "email": "damilareatunbi@gmail.com",
      "Username": "Damilare",
      "phoneNumber": 8100717362,
      "country": "Nigeria",
      "institution": "University of Ilorin",
      "department": "Electrical and Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "ETEYEN",
      "lName": "UYO",
      "email": "uyoeteyen@gmail.com",
      "Username": "ETEYEN",
      "phoneNumber": 8032485982,
      "country": "Nigeria",
      "institution": "The university of Ibadan",
      "department": "Electrical/Electronics Engineering",
      "category": "Local Participant"
    },
    {
      "fName": "Maxwell",
      "lName": "Chima",
      "email": "chymax20@yahoo.com",
      "Username": "Maxwell",
      "phoneNumber": 8067252222,
      "country": "Nigeria",
      "institution": "Federal Polytechnic Nekede, Owerri, Imo State",
      "department": "Electrical/Electronics Engineering",
      "category": "Local Participant"
    },
    {
      "fName": "Jeremiah",
      "lName": "Dosu",
      "email": "dosujerry1997@gmail.com",
      "Username": "Jeremiah",
      "phoneNumber": 9041775693,
      "country": "Nigeria",
      "institution": "Federal University of Technology Minna",
      "department": "Department of Mechatronics Engineering",
      "category": "Local Student"
    },
    {
      "fName": "Richard",
      "lName": "Olarewaju",
      "email": "dayorich2018@gmail.com",
      "Username": "Richard",
      "phoneNumber": 7060747826,
      "country": "Nigeria",
      "institution": "UNIVERSITY OF IBADAN",
      "department": "ELECTRICAL/ELECTRONIC ENGINEERING",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Joseph",
      "lName": "Fadiji",
      "email": "fadiji.joseph@st.futminna.edu.ng",
      "Username": "Joseph",
      "phoneNumber": 8091121186,
      "country": "Nigeria",
      "institution": "Federal University of Technology",
      "department": "Computer Engineering",
      "category": "Local Student"
    },
    {
      "fName": "Okezie ",
      "lName": "Ozue",
      "email": "Okeziepg@gmail.com",
      "Username": "Okezie ",
      "phoneNumber": 7038262179,
      "country": "Nigeria",
      "institution": "",
      "department": "Electrical And Electronics Engineering ",
      "category": "Local Participant"
    },
    {
      "fName": "Goodness",
      "lName": "Adedeji",
      "email": "goodnessadedeji7@gmail.com",
      "Username": "Goodness",
      "phoneNumber": 8101006726,
      "country": "Nigeria",
      "institution": "",
      "department": "Department of Mechatronics Engineering",
      "category": "Local Student"
    },
    {
      "fName": "Olalekan",
      "lName": "Bada",
      "email": "gens3000@gmail.com",
      "Username": "Olalekan",
      "phoneNumber": 7055068384,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronic Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "OPEYEMI",
      "lName": "ADEBISI",
      "email": "isaacopeyemi13@gmail.com",
      "Username": "OPEYEMI",
      "phoneNumber": 7030221494,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "Afis",
      "lName": "Akande",
      "email": "nugget4best2004@gmail.com",
      "Username": "Afis",
      "phoneNumber": 8038005191,
      "country": "Nigeria",
      "institution": "University of Ibadan",
      "department": "Electrical and Electronics Engineering",
      "category": "Postgraduate Session Participant"
    },
    {
      "fName": "ADEAGBO ",
      "lName": "MONSURU",
      "email": "Adeagbomonsoor@gmail.com",
      "Username": "ADEAGBO ",
      "phoneNumber": 8034648769,
      "country": "Nigeria",
      "institution": "Lautech",
      "department": "Computer Engineering ",
      "category": "Postgraduate Session Participant"
    }
   ]